---

- name: update packages and install apache2
  become: yes
  hosts: all
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: create a file
      ansible.builtin.file:
        path: /var/www/html/info.php