---

- name: update packages and install apache2
  become: yes
  hosts: all
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: copy the file info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: apache2 service start and enable
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started